# Generated by Django 5.1.3 on 2024-11-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('is_manager', models.BooleanField(blank=True, default=False, null=True)),
                ('is_doctor', models.BooleanField(blank=True, default=False, null=True)),
                ('is_patient', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
